Document: bash-unit
Title: Debian bash-unit Manual
Author: <insert document author here>
Abstract: This manual describes what bash-unit is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/bash-unit/bash-unit.sgml.gz

Format: postscript
Files: /usr/share/doc/bash-unit/bash-unit.ps.gz

Format: text
Files: /usr/share/doc/bash-unit/bash-unit.text.gz

Format: HTML
Index: /usr/share/doc/bash-unit/html/index.html
Files: /usr/share/doc/bash-unit/html/*.html
